### ISSUE TITLE
test

### ISSUE THREAD

**Issue by rafalsk** [trevp/ref10_extract#8]

**Comment by trevp** [comment]
This code is ancient and obsolete, you should use the newer code here:

https://github.com/WhisperSystems/curve25519-java/tree/master/android/jni/ed25519
https://github.com/WhisperSystems/libsignal-protocol-c/tree/master/src/curve25519/ed25519

I'll delete this repo soon so it won't distract other people.

**Comment by rafalsk** [comment]
the parts I'm interested in is signature/verification using Curve25519 keys, do the new source codes provide such functionallity?
